admin_panel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/',views.dashboard,name='dashboard'),
    path('addProduct/',views.add_product, name="add_product"),
    path('updateProduct/<int:id>',views.update_product, name="update_product"),
    path('deleteProduct/<int:id>',views.delete_product,name="delete_product" )
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name="home"),
    path('addProduct/',views.add_product, name="add_product"),
    path('productDetails/<int:id>', views.product_details, name='product_details'),
    #path('addToCart/',views.add_to_cart, name="add_to_cart"),
    path('addToCart/<int:product_id>',views.add_to_cart, name="add_to_cart"),
    path('cart/',views.view_cart, name="cart"),
    path('delete-from-cart/<int:id>',views.delete_item_from_cart, name="delete_from_cart")
]

shopping/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/',include('users.urls')),
    path('admin-panel/',include('admin_panel.urls')),
    path('payment/',include('payment.urls')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Product(models.Model):
    name=models.CharField(max_length=100)
    price=models.IntegerField()
    quantity=models.IntegerField()
    image=models.FileField(upload_to='uploads/',null=True)
    
class Cart(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, null=True,blank=True)
    created_at=models.DateTimeField(auto_now_add=True,null=True)

class CartItem(models.Model):
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE,related_name='items',null=True)
    product=models.ForeignKey(Product,on_delete=models.CASCADE,related_name='cart_items',null=True)
    quantity=models.PositiveIntegerField(default=1)

admin_panel/forms.py
from django import forms 
from main.models import Product

class AddProduct(forms.ModelForm):
    class Meta:
        model=Product
        fields=['name','price','quantity','image']
        
class UpdateProduct(forms.ModelForm):
    class Meta:
        model=Product
        fields=['name','price','quantity','image']

admin_panel/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required,user_passes_test
from main.models import Product
from .forms import AddProduct,UpdateProduct
# Create your views here.
def is_admin(user):
    return user.is_superuser

@login_required
@user_passes_test(is_admin)  
def dashboard(request):
    products=Product.objects.all()
    return render(request,'admin_panel/dashboard.html',{'products':products})

@login_required
@user_passes_test(is_admin)
def add_product(request):
    if request.method=="POST":
        form=AddProduct(request.POST,request.FILES)
        if form.is_valid():
            form.save()    
            return redirect("home")
    
    form=AddProduct()
    context={
        'form':form
    }
    return render(request,'main/addProduct.html',context)

@login_required
@user_passes_test(is_admin)
def update_product(request,id):
    product= Product.objects.get(id=id)
    if request.method=="POST":
        form=UpdateProduct(request.POST,request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
    else:
        form = UpdateProduct(instance=product)
    return render(request,'admin_panel/update_product.html',{'form':form,'product':product})    

@login_required
@user_passes_test(is_admin)
def delete_product(request,id):
    product=Product.objects.get(id=id)
    if request.method=="POST":
        product.delete()
        return redirect('dashboard')
    return render(request,'admin_panel/confirm_delete.html',{'product':product})
    

admin_panel/templates/admin_panel/addProduct.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AddProduct</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    {% include "main/menu.html" %}
    <h2 class="text-center font-bold text-2xl my-5 text-green-700">Add a new  product </h2>
   <div class="flex justify-center">
    <form action="" method="post" enctype='multipart/form-data' class="border p-5 rounded-lg shadow-lg" >
        {% csrf_token %}
        {% comment %} {{form}} {% endcomment %}
       <div class='flex flex-col gap-3'>
            <div class='flex flex-col gap-[5px]'>
                <label for="id_name">Name:</label>
                <input type="text" name="name" maxlength="100" required="" id="id_name" class="border-[2px] rounded-md border-gray-400">   
            </div>
            <div class='flex flex-col gap-[5px]'>
                <label for="id_price">Price:</label>
                <input type="number" name="price" required="" id="id_price" class="border-[2px] rounded-md border-gray-400">   
            </div>
            <div class='flex flex-col gap-[5px]'>
                <label for="id_quantity">Quantity:</label>
                <input type="number" name="quantity" required="" id="id_quantity" class="border-[2px] rounded-md border-gray-400"> 
            </div>
            <div class='flex flex-col gap-[5px]'>
                <label for="id_image">Image:</label>
                <input type="file" name="image" required="" id="id_image">   
            </div>
            <button type="submit" class="border-[2px] border-black px-3 py-1 rounded-lg mt-[20px] bg-green-300 hover:bg-green-500">Add Product</button>
       </div>

    </form>
   </div>
</body>
</html>

admin_panel/templates/admin_panel/confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>delete confirmation</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 flex justify-center items-center h-screen">
    <div class="bg-white shadow-md p-5 w-full max-w-md rounded-lg">
        <h2 class="text-2xl font-bold mb-4 text-center">Confirm delete</h2>
        <p class="font-medium text-xl mb-5">Are you sure you want to delete the product?</p>
        <div class="flex justify-center">
            <form action="" method="post">
                {% csrf_token %}
                <button type="submit" class="bg-red-500 text-white py-2 px-4 rounded hover:bg-red-700">delete</button>
                <a href="{% url 'dashboard' %}" class="bg-gray-300 text-white py-2 px-4 rounded hover:bg-gray-500">cancel</a>
            </form>
        </div>
    </div>
    
</body>
</html>

admin_panel/templates/admin_panel/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>dashboard</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    {% include "main/menu.html" %}
  <div class="flex">
    {% include "admin_panel/sidebar.html" %}
    <div class="w-full overflow-x-auto">
        <table class="min-w-full bg-white border border-gray-200">
            <thead>
                <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                    <th class="py-3 px-5 text-left">Name</th>
                    <th class="py-3 px-5 text-left">Price</th>
                    <th class="py-3 px-5 text-left">Quantity</th>
                    <th class="py-3 px-5 text-left">Image</th>
                    <th class="py-3 px-5 text-left">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        <td class="py-3 px-5 text-left">{{product.name}}</td>
                        <td class="py-3 px-5 text-left">{{product.price}}</td>
                        <td class="py-3 px-5 text-left">{{product.quantity}}</td>
                        <td class="py-3 px-5 text-left">
                            {% if product.image %}
                                <img src="{{product.image.url}}" alt="Product Image" class="h-10 w-10 rounded">
                            {% endif %}
                        </td>
                        <td class="py-3 px-5">
                            <div class="flex items-center gap-4">
                                <a href="{% url 'update_product' product.id %}" class="text-green-600 hover:text-800">update</a>
                           
                                    <a href="{% url 'delete_product' product.id%}" class="text-red-600 hover:red-800">delete</a>
                               
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
  </div>
</body>
</html>

admin_panel/templates/admin_panel/sidebar.html
<div class="w-64 h-screen bg-gray-800 text-white flex flex-col">
    <div class="p-6 text-2xl font-semibold text-center border-b border-gray-700">
        <h2>Admin Panel</h2>
    </div>
    <ul class="mt-6 space-y-2 px-2">
        <li>
            <a href="{% url 'dashboard' %}" class="block px-4 py-2 text-gray-200 hover:bg-gray-700 rounded">All products</a>
        </li>
        <li>
            <a href="{% url 'add_product' %}" class="block px-4 py-2 text-gray-200 hover:bg-gray-700 rounded">Add products</a>
        </li>
        <li>
            <a href="#" class="block px-4 py-2 text-gray-200 hover:bg-gray-700 rounded">All users</a>
        </li>
    </ul>
</div>

admin_panel/templates/admin_panel/update_product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>update product</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    {% include "main/menu.html" %}
    <h2 class="text-center font-bold text-2xl my-5 text-green-700">Update product {{product.name}}</h2>
   <div class="flex justify-center">
    <form action="" method="post" enctype='multipart/form-data' class="border p-5 rounded-lg shadow-lg" >
        {% csrf_token %}
        {% comment %} {{form}} {% endcomment %}
       <div class='flex flex-col gap-3'>
            <div class='flex flex-col gap-[5px]'>
                <label for="id_name">Name:</label>
                <input type="text" name="name" value="{{product.name|default_if_none:""}}" maxlength="100" required="" id="id_name" class="border-[2px] rounded-md border-gray-400">   
            </div>
            <div class='flex flex-col gap-[5px]'>
                <label for="id_price">Price:</label>
                <input type="number" name="price" value="{{form.price.value | default_if_none:""}}" required="" id="id_price" class="border-[2px] rounded-md border-gray-400">   
            </div>
            <div class='flex flex-col gap-[5px]'>
                <label for="id_quantity">Quantity:</label>
                <input type="number" name="quantity" value="{{form.quantity.value | default_if_none:""}}" required="" id="id_quantity" class="border-[2px] rounded-md border-gray-400"> 
            </div>
            <div class='flex flex-col gap-[5px]'>
                <label for="id_image">Image:</label>
                <input type="file" name="image" id="id_image">   
            </div>
            <button type="submit" class="border-[2px] border-black px-3 py-1 rounded-lg mt-[20px] bg-green-300 hover:bg-green-500">Update Product</button>
       </div>

    </form>
   </div>
</body>
</html>